### PR TITLE
New Feature - Ability to provide 3rd party categories and technologies - 2nd attempt

### PR DESCRIPTION
**Pull request by BigFoxMedia**
Users can now pass an object containing custom categories & technologies, conforming and validated against the original schema.json.
The code isn't very clean but works without bugs, as far as I'm aware of.
I'm also sure you can do a better job at the README.md file than me, but I hope you would find this commonly useful enough to incorporate it as a feature.

### CODE REVIEW

**Comment by BigFoxMedia** [comment]
Looks like the build is failing, but due to my lack of CI & GIT experience, I'm unsure what is the reason or how to investigate it. 
From testing myself, looks like it's working on my local machine. 
Hope you can take a look and help me to finalize this feature :)

**Comment by BigFoxMedia** [comment]
About that build failing.. my hunch is that it's due to my improper addition of the validate package. I needed this package to validate the external object against the schema, but I feel that I added it somehow wrong

**Comment by Kikobeats** [comment]
Can you explain a bit what's your use case and why do you need this?

technologies and categories are programmatically fetched when you install the library:
https://github.com/Kikobeats/simple-wappalyzer/blob/master/scripts/postinstall.js#L11

I can add support for passing your own schema if you want, but I'm not interested in keeping a `schema.json` associated with the library since it's dynamically fetched.

**Comment by BigFoxMedia** [comment]
Hi Kiko,

So the idea is this, wappalyzer is well maintained and updates new technologies all of the time. However, I would like to use it to identify other-additional technologies not present in the technologies.json.

For example, it is not used at present to identify ad networks such as DSPs and SSPs, or ad exchanges. 
Other users might want to identify other technology sets.

The feature I proposed allows the user to use the same underlying wappalyzer analyzer but with custom technologies provided by the user in an object.

In my opinion this takes an already powerful tool which is wappalyzer and makes it dynamic to work on any number of ttechnologies that are not currently supported for any users specific needs.

What I meant about the schema.json in my previous comment was that the object that the user provides is checked against the schema to make sure that the object adhers to it, so not to get errors from Wappalyzer core. If the Object the user provided does not adhere to guidelines of the schema, the user gets a console log with exact rows and missing or wrong data.

Thanks,
Ed.

**Comment by Kikobeats** [comment]
I can see your intentions are good, but I prefer to keep this library as small as possible, not being really interested in to increment the complexity of the library for adding a very specific use case.

One thing I can do is to expose the methods used by wappalyzer for setup categories and technologies:

https://github.com/Kikobeats/simple-wappalyzer/blob/bc67e5d368b9bcad0099ca22d2dc237e37e691a7/src/index.js#L12

then, validation can be a different library that can be used in combination with this.

**Comment by BigFoxMedia** [comment]
No worries you can close the commit :) I will use this feature in my fork than ;-)

**Pull request closed without merging**
